### PR TITLE
Add new ledger proxies for both testnets

### PR DESCRIPTION
**Pull request by blushi**
## Description

ref: https://github.com/regen-network/regen-registry/issues/838

Since we need to have both hambach and redwood ledger rpc/REST proxies up for the future permanent branches `hambach` and `redwood` on regen-web, I've added some `exp` additional proxies for hambach.

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [x] targeted `dev` branch
- [x] provided a link to the relevant issue or specification
- [x] reviewed "Files changed" and left comments if necessary
- [x] confirmed all tests passed
- [ ] submit a PR against `master` branch after this one (and other PRs depending on this one, e.g. on regen-network/regen-web, if applicable) get merged

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**.*

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by blushi** [comment]
> i'd be curious to hear more about what we need to consider in order to make the switch from hambach to mainnet in production. is there an open issue for that?
 
We would need to update LEDGER_TENDERMINT_RPC and LEDGER_REST_ENDPOINT env var on heroku production registry-server to point to mainnet endpoints.

> one detail, does exp mean experimental?

yes, do you think we should use the full word instead? But that might result in quite long endpoints names.

**Comment by wgwz** [comment]
> We would need to update LEDGER_TENDERMINT_RPC and LEDGER_REST_ENDPOINT env var on heroku production registry-server to point to mainnet endpoints.

I see, are there any side-effects of making that change in terms of the data available to the regen web? Like would that affect project pages in some way? we can talk through this in another place if it makes more sense.

> yes, do you think we should use the full word instead? But that might result in quite long endpoints names.

no, i wouldn't want to use the full name for that. if anything, maybe a small comment/s documenting this in either `server/.env-example` or in the README would be nice.

**Comment by blushi** [comment]
> I see, are there any side-effects of making that change in terms of the data available to the regen web? Like would that affect project pages in some way? we can talk through this in another place if it makes more sense.

As I said in the PR description, this will affect some project pages that use hambach to pull some tx data (which is accessible from the "view on ledger" button from the documentation table) so this is something we need to discuss with the rest of the team, I'll plan to bring this up during sprint planning.

> no, i wouldn't want to use the full name for that. if anything, maybe a small comment/s documenting this in either server/.env-example or in the README would be nice.

sounds good.

**Comment by blushi** [comment]
After discussing this during the sprint planning, we're gonna need to keep some temporary support for hambach on registry.regen.network, while at the same time being able to interact with mainnet.

**Pull request merged**
