### PR TITLE
Add credit batch denoms into credit vintage

### PR DESCRIPTION
**Pull request by wgwz**
## Description

Closes: https://github.com/regen-network/regen-registry/issues/833

This PR adds a `batch_denom` column to the `credit_vintage` table. The most important files to review are:

1. `sql/R__issue_credits.sql`
2. `server/__tests__/db/functions/issue_credits.test.ts`
3. `sql/V1_81__add_batch_denom_to_credit_vintage.sql`

After making this change, the corresponding graphql mutation `issueCredits` will accept an optional parameter called `batchDenom`.

I believe this is an example of where it may need [to be updated][1] in relation to https://github.com/regen-network/regen-registry/issues/802. I'm curious to learn about the corresponding changes on the front-end.

[1]: https://github.com/regen-network/regen-web/blob/master/web-registry/src/pages/CreditsIssue.tsx#L169

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [x] targeted `dev` branch
- [x] provided a link to the relevant issue or specification
- [x] reviewed "Files changed" and left comments if necessary
- [x] confirmed all tests passed
- [ ] submit a PR against `master` branch after this one (and other PRs depending on this one, e.g. on regen-network/regen-web, if applicable) get merged

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**.*

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by wgwz** [comment]
Hi @blushi, I wanted to ask a bit about the `issue_credits` function in regard to adding the `batch_denom` optional parameter there.

Suppose the `batch_denom` is not specifed, do we want a default value of null to be inserted? I'm thinking that's yes.

If that's true, then I guess I would need to add that to these insert statements:

https://github.com/regen-network/registry-server/pull/124/files#diff-36db416e1e96dd9f5fc19c0e03737512f2fcc363223fa9a4d9c8ccaab0f0b3bdR113-R116

https://github.com/regen-network/registry-server/pull/124/files#diff-36db416e1e96dd9f5fc19c0e03737512f2fcc363223fa9a4d9c8ccaab0f0b3bdR196-R199

**Comment by wgwz** [comment]
Hi @blushi I'm having some trouble figuring out what's causing [the test failures][1] I'm seeing. So far this is what I've done in this PR:

- Adding the `batch_denom` column to `credit_vintage`
- Modify the `issue_credits` function to accept an optional `batch_denom`
- Modify the `issue_credits` function to insert `batch_denom` (I'm not sure I've done this correctly)
- Modify various locations in the test code to account for this new `batch_denom` argument (I'm not sure I've done this correctly)

I'm going to take another look at this with fresh eyes tomorrow. But any advice or guidance will be appreciated :-)

[1]: https://gist.github.com/wgwz/2fced721bbfef8e109b6750585ed5d88

**Comment by blushi** [comment]
@wgwz Since it has 'strict', the function won't run as long as one of its parameter is null (here `batch_denom`), see https://www.postgresql.org/docs/current/sql-createfunction.html and look for "STRICT". I guess we can safely remove `strict` from the function in this case from here: https://github.com/regen-network/registry-server/blob/kyle/833-credit-batch-denoms-per-project/sql/R__issue_credits.sql#L219

**Comment by wgwz** [comment]
Hi @blushi , indeed, that worked! Thanks! Was there a reason that we had that set to `strict`? At least all the tests are passing now.

I'm going to look to see if there are any tests I should add for the new field. I'm guessing it'll be good to write a test where the `batch_denom` is a non-null value and something realistic.

**Comment by wgwz** [comment]
@blushi After thinking about it some more I can't actually think of any super meaningful tests to add here, so what I did is just add a simple assertion about `batch_denom` to the first "issue credits" tests in `issue_credits.test.ts`. If you have any suggestions for a test I should add or modify, let me know. It's just that it's either going to be a null or a text value, and I'm sure if it makes sense to test other cases. I'm guessing the validation is going to happen at a higher-level in our program, rather than in our database, so I don't think makes sense to write a test here that's like "what happens when batch_denom is an integer value?"

**Comment by blushi** [comment]
> @blushi After thinking about it some more I can't actually think of any super meaningful tests to add here, so what I did is just add a simple assertion about `batch_denom` to the first "issue credits" tests in `issue_credits.test.ts`. If you have any suggestions for a test I should add or modify, let me know. It's just that it's either going to be a null or a text value, and I'm sure if it makes sense to test other cases. I'm guessing the validation is going to happen at a higher-level in our program, rather than in our database, so I don't think makes sense to write a test here that's like "what happens when batch_denom is an integer value?"

Yeah I guess you could just have a non null `batch_denom`, then based on the credit vintage id returned by the function, get the corresponding credit vintage row and verify that `batch_denom` is the same there. You can just add that check to the first test 'issues credits'

**Comment by wgwz** [comment]
Hi @blushi, I think this may be ready to merge. I updated the first issue credits test to use a realistic string value for it's assertion. @haveanicedavid just wanted to ping you on this as well for your review, thanks!

**Review by haveanicedavid — APPROVED** [review]
Looks good to me!

**Review by mhagel — APPROVED** [review]

**Comment by wgwz** [comment]
@blushi I just want to confirm your approval on this one before merging it :)

**Review by haveanicedavid — APPROVED** [review]

**Review by blushi — APPROVED** [review]

**Pull request merged**
